name: pift
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - numpy
  - pandas
  - pyarrow
  - scikit-learn
  - scipy
  - matplotlib
  - seaborn
  - tqdm
  - pyyaml
  - requests
  - jupyter
  - ipykernel
  - pip:
      - torch
      - rtdl-revisiting-models
      - xgboost
      - einops
      - tensorboard
      - wandb
      - pytest
      # PIFT v3 NSI dependencies
      - git+https://github.com/Blealtan/efficient-kan.git
      - pykan
